### ISSUE TITLE
NameError: global name 'get_whitespace_from_line_begin' is not defined

### ISSUE THREAD

**Issue by gh640** [molnarmark/carbonSublime#10]
When I tried to run the command `carbon_sublime` after installing the dev HEAD of this package to my Sublime Text, the following error occurred and it didn't work.

```text
>>> view.run_command('carbon_sublime')
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/.../Sublime Text 3/Packages/carbonSublime/carbonSublime.py", line 96, in run
    code = self.normalize_code()
  File "/.../Sublime Text 3/Packages/carbonSublime/carbonSublime.py", line 107, in normalize_code
    whitespace = convert_tabs_using_tab_size(view, get_whitespace_from_line_begin(view, view.sel()[0]))
NameError: global name 'get_whitespace_from_line_begin' is not defined
```

`get_whitespace_from_line_begin` should be `get_whitespace_from_line_beginning`, I believe.

https://github.com/molnarmark/carbonSublime/blob/master/carbonSublime.py#L89

**Comment by molnarmark** [comment]
Fixed. Thanks.

**Comment by gh640** [comment]
Thanks!
